### ISSUE TITLE
Do not update the post/page if nothing change

### ISSUE THREAD

**Issue by ggrossetie** [neo4j-contrib/wordpress-publish-gradle-plugin#17]
We could compare the md5sum of the content but we should also make sure that the metadata didn't not change (author, tags, medias, categories, taxonomies...).

Maybe we could compare the md5sum of the source (i.e. the AsciiDoc document because it contains the content and all the metadata)

**Comment by jexp** [comment]
yep that sounds like a good idea. And store it as an extra page attribute.
